#ifndef _I2C_H
#define _I2C_H

enum i2c_config {
	I2C_CONFIG_ENABLE = I2C_CTRL_EN,
};

enum i2c_flags {
	I2C_FLAG_SSTOP   = I2C_IF_SSTOP,
	I2C_FLAG_CLTO    = I2C_IF_CLTO,
	I2C_FLAG_BITO    = I2C_IF_BITO,
	I2C_FLAG_RXUF    = I2C_IF_RXUF,
	I2C_FLAG_TXOF    = I2C_IF_TXOF,
	I2C_FLAG_BUSHOLD = I2C_IF_BUSHOLD,
	I2C_FLAG_BUSERR  = I2C_IF_BUSERR,
	I2C_FLAG_ARBLOST = I2C_IF_ARBLOST,
	I2C_FLAG_MSTOP   = I2C_IF_MSTOP,
	I2C_FLAG_NACK    = I2C_IF_NACK,
	I2C_FLAG_ACK     = I2C_IF_ACK,
	I2C_FLAG_RXDATAV = I2C_IF_RXDATAV,
	I2C_FLAG_TXBL    = I2C_IF_TXBL,
	I2C_FLAG_TXC     = I2C_IF_TXC,
	I2C_FLAG_ADDR    = I2C_IF_ADDR,
	I2C_FLAG_RSTART  = I2C_IF_RSTART,
	I2C_FLAG_START   = I2C_IF_START,
};

enum i2c_pins {
	I2C_PINS_NONE     = 0,
	I2C_PINS_DISABLE0 = I2C_ROUTE_LOCATION_LOC0,
	I2C_PINS_ENABLE0  = I2C_ROUTE_LOCATION_LOC0 | I2C_ROUTE_SCLPEN | I2C_ROUTE_SDAPEN,
	I2C_PINS_DISABLE1 = I2C_ROUTE_LOCATION_LOC1,
	I2C_PINS_ENABLE1  = I2C_ROUTE_LOCATION_LOC1 | I2C_ROUTE_SCLPEN | I2C_ROUTE_SDAPEN,
	I2C_PINS_DISABLE2 = I2C_ROUTE_LOCATION_LOC2,
	I2C_PINS_ENABLE2  = I2C_ROUTE_LOCATION_LOC2 | I2C_ROUTE_SCLPEN | I2C_ROUTE_SDAPEN,
	I2C_PINS_DISABLE3 = I2C_ROUTE_LOCATION_LOC3,
	I2C_PINS_ENABLE3  = I2C_ROUTE_LOCATION_LOC3 | I2C_ROUTE_SCLPEN | I2C_ROUTE_SDAPEN,
	I2C_PINS_DISABLE4 = I2C_ROUTE_LOCATION_LOC4,
	I2C_PINS_ENABLE4  = I2C_ROUTE_LOCATION_LOC4 | I2C_ROUTE_SCLPEN | I2C_ROUTE_SDAPEN,
	I2C_PINS_DISABLE5 = I2C_ROUTE_LOCATION_LOC5,
	I2C_PINS_ENABLE5  = I2C_ROUTE_LOCATION_LOC5 | I2C_ROUTE_SCLPEN | I2C_ROUTE_SDAPEN,
	I2C_PINS_DISABLE6 = I2C_ROUTE_LOCATION_LOC6,
	I2C_PINS_ENABLE6  = I2C_ROUTE_LOCATION_LOC6 | I2C_ROUTE_SCLPEN | I2C_ROUTE_SDAPEN,
};

#endif
