#ifndef _LEUART_H
#define _LEUART_H

enum leuart_config {
	LEUART_CONFIG_8N1 = LEUART_CTRL_DATABITS_EIGHT | LEUART_CTRL_PARITY_NONE | LEUART_CTRL_STOPBITS_ONE,
	LEUART_CONFIG_8N2 = LEUART_CTRL_DATABITS_EIGHT | LEUART_CTRL_PARITY_NONE | LEUART_CTRL_STOPBITS_TWO,
	LEUART_CONFIG_8O1 = LEUART_CTRL_DATABITS_EIGHT | LEUART_CTRL_PARITY_ODD  | LEUART_CTRL_STOPBITS_ONE,
	LEUART_CONFIG_8O2 = LEUART_CTRL_DATABITS_EIGHT | LEUART_CTRL_PARITY_ODD  | LEUART_CTRL_STOPBITS_TWO,
};

enum leuart_pins {
	LEUART_PINS_NONE  = 0,
	LEUART_PINS_RX0   = LEUART_ROUTE_LOCATION_LOC0 | LEUART_ROUTE_RXPEN,
	LEUART_PINS_TX0   = LEUART_ROUTE_LOCATION_LOC0 | LEUART_ROUTE_TXPEN,
	LEUART_PINS_RXTX0 = LEUART_ROUTE_LOCATION_LOC0 | LEUART_ROUTE_TXPEN | LEUART_ROUTE_RXPEN,
	LEUART_PINS_RX1   = LEUART_ROUTE_LOCATION_LOC1 | LEUART_ROUTE_RXPEN,
	LEUART_PINS_TX1   = LEUART_ROUTE_LOCATION_LOC1 | LEUART_ROUTE_TXPEN,
	LEUART_PINS_RXTX1 = LEUART_ROUTE_LOCATION_LOC1 | LEUART_ROUTE_TXPEN | LEUART_ROUTE_RXPEN,
	LEUART_PINS_RX2   = LEUART_ROUTE_LOCATION_LOC2 | LEUART_ROUTE_RXPEN,
	LEUART_PINS_TX2   = LEUART_ROUTE_LOCATION_LOC2 | LEUART_ROUTE_TXPEN,
	LEUART_PINS_RXTX2 = LEUART_ROUTE_LOCATION_LOC2 | LEUART_ROUTE_TXPEN | LEUART_ROUTE_RXPEN,
	LEUART_PINS_RX3   = LEUART_ROUTE_LOCATION_LOC3 | LEUART_ROUTE_RXPEN,
	LEUART_PINS_TX3   = LEUART_ROUTE_LOCATION_LOC3 | LEUART_ROUTE_TXPEN,
	LEUART_PINS_RXTX3 = LEUART_ROUTE_LOCATION_LOC3 | LEUART_ROUTE_TXPEN | LEUART_ROUTE_RXPEN,
	LEUART_PINS_RX4   = LEUART_ROUTE_LOCATION_LOC4 | LEUART_ROUTE_RXPEN,
	LEUART_PINS_TX4   = LEUART_ROUTE_LOCATION_LOC4 | LEUART_ROUTE_TXPEN,
	LEUART_PINS_RXTX4 = LEUART_ROUTE_LOCATION_LOC4 | LEUART_ROUTE_TXPEN | LEUART_ROUTE_RXPEN,
	LEUART_PINS_RX5   = LEUART_ROUTE_LOCATION_LOC5 | LEUART_ROUTE_RXPEN,
	LEUART_PINS_TX5   = LEUART_ROUTE_LOCATION_LOC5 | LEUART_ROUTE_TXPEN,
	LEUART_PINS_RXTX5 = LEUART_ROUTE_LOCATION_LOC5 | LEUART_ROUTE_TXPEN | LEUART_ROUTE_RXPEN,
};

enum leuart_flags {
	LEUART_FLAG_SIGNAL_FRAME    = LEUART_IF_SIGF,
	LEUART_FLAG_START_FRAME     = LEUART_IF_STARTF,
	LEUART_FLAG_MP_ADDRESS      = LEUART_IF_MPAF,
	LEUART_FLAG_FRAMING_ERROR   = LEUART_IF_FERR,
	LEUART_FLAG_PARITY_ERROR    = LEUART_IF_PERR,
	LEUART_FLAG_TX_OVERFLOW     = LEUART_IF_TXOF,
	LEUART_FLAG_RX_UNDERFLOW    = LEUART_IF_RXUF,
	LEUART_FLAG_RX_OVERFLOW     = LEUART_IF_RXOF,
	LEUART_FLAG_RX_DATA_VALID   = LEUART_IF_RXDATAV,
	LEUART_FLAG_TX_BUFFER_LEVEL = LEUART_IF_TXBL,
	LEUART_FLAG_TX_COMPLETE     = LEUART_IF_TXC,
};

#endif
