#ifndef _TIMER_H
#define _TIMER_H

enum timer_config {
	TIMER_CONFIG_DEBUGRUN   = TIMER_CTRL_DEBUGRUN,
	TIMER_CONFIG_ONESHOT    = TIMER_CTRL_OSMEN,
	TIMER_CONFIG_SYNC       = TIMER_CTRL_SYNC,
	TIMER_CONFIG_UP         = TIMER_CTRL_MODE_UP,
	TIMER_CONFIG_DOWN       = TIMER_CTRL_MODE_DOWN,
	TIMER_CONFIG_UPDOWN     = TIMER_CTRL_MODE_UPDOWN,
	TIMER_CONFIG_QDEC       = TIMER_CTRL_MODE_QDEC,
};

enum timer_pins {
	TIMER_PINS_LOCATION0    = TIMER_ROUTE_LOCATION_LOC0,
	TIMER_PINS_LOCATION1    = TIMER_ROUTE_LOCATION_LOC1,
	TIMER_PINS_LOCATION2    = TIMER_ROUTE_LOCATION_LOC2,
	TIMER_PINS_LOCATION3    = TIMER_ROUTE_LOCATION_LOC3,
	TIMER_PINS_LOCATION4    = TIMER_ROUTE_LOCATION_LOC4,
	TIMER_PINS_LOCATION5    = TIMER_ROUTE_LOCATION_LOC5,
	TIMER_PINS_LOCATION6    = TIMER_ROUTE_LOCATION_LOC6,
	TIMER_PINS_CC2_ENABLE   = TIMER_ROUTE_CC2PEN,
	TIMER_PINS_CC1_ENABLE   = TIMER_ROUTE_CC1PEN,
	TIMER_PINS_CC0_ENABLE   = TIMER_ROUTE_CC0PEN,
};

enum timer_cc_config {
	TIMER_CC_CONFIG_INVERT  = TIMER_CC_CTRL_OUTINV,
	TIMER_CC_CONFIG_CAPTURE = TIMER_CC_CTRL_MODE_INPUTCAPTURE,
	TIMER_CC_CONFIG_COMPARE = TIMER_CC_CTRL_MODE_OUTPUTCOMPARE,
	TIMER_CC_CONFIG_PWM     = TIMER_CC_CTRL_MODE_PWM,
};

#endif
